#!/bin/sh
# Regenerates the app icon set from design/icon.svg.
#
# Uses ImageMagick (with -type TrueColorAlpha, forcing plain RGBA output)
# rather than sips for the resize step, mainly to get consistent, known
# output -- sips's PNG color-type choice varies with image content.
#
# Requires: rsvg-convert, ImageMagick (magick).
#
# design/icon-toolbar.svg is kept only as historical reference -- it was
# built to work around Safari-specific toolbar-icon bugs (near-black
# backgrounds failing to load, dark colors getting auto-tinted blue) from
# when Lodestone was a Safari Web Extension. None of that applies now that
# Lodestone is a native menu-bar app; the menu-bar status item icon is a
# separate monochrome template asset, not generated by this script.

set -e
cd "$(dirname "$0")/.."

SVG="design/icon.svg"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

rsvg-convert -w 1024 -h 1024 "$SVG" -o "$TMP/icon-1024.png"

resize() {
  # $1 = size (square), $2 = output path
  magick "$TMP/icon-1024.png" -resize "${1}x${1}" -type TrueColorAlpha -define png:color-type=6 -strip "$2"
}

APPICON="Lodestone/Lodestone/Assets.xcassets/AppIcon.appiconset"

resize 16 "$APPICON/icon_16x16.png"
resize 32 "$APPICON/icon_16x16@2x.png"
resize 32 "$APPICON/icon_32x32.png"
resize 64 "$APPICON/icon_32x32@2x.png"
resize 128 "$APPICON/icon_128x128.png"
resize 256 "$APPICON/icon_128x128@2x.png"
resize 256 "$APPICON/icon_256x256.png"
resize 512 "$APPICON/icon_256x256@2x.png"
resize 512 "$APPICON/icon_512x512.png"
magick "$TMP/icon-1024.png" -type TrueColorAlpha -define png:color-type=6 -strip "$APPICON/icon_512x512@2x.png"

echo "App icon regenerated as truecolor RGBA. Rebuild in Xcode."
